services:
  app:
    build: .
    container_name: fastapi-yt
    # ports:
    #   - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
      - ./cookies.txt:/app/cookies.txt:ro
    restart: unless-stopped
