[project]
name = "yt-dlp-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.2",
    "python-dotenv>=1.2.1",
    "yt-dlp>=2026.2.4",
]
